/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => CanvasNoteSameFolderPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var CanvasNoteSameFolderPlugin = class extends import_obsidian.Plugin {
  async onload() {
    this.registerEvent(
      this.app.vault.on("create", async (file) => {
        await this.handleFileCreation(file);
      })
    );
  }
  /**
   * Main handler for file creation events
   */
  async handleFileCreation(file) {
    var _a;
    if (!(file instanceof import_obsidian.TFile))
      return;
    if (!file.path.endsWith(".md"))
      return;
    if (!this.isCreatedFromCanvas(file))
      return;
    const canvasFile = this.getActiveCanvasFile();
    if (!canvasFile)
      return;
    const targetFolderPath = this.getTargetFolderPath(canvasFile);
    if (!targetFolderPath)
      return;
    if (((_a = file.parent) == null ? void 0 : _a.path) === targetFolderPath)
      return;
    await this.ensureFolderExists(targetFolderPath);
    const uniqueFileName = await this.getUniqueFileName(targetFolderPath, file.name);
    const targetPath = `${targetFolderPath}/${uniqueFileName}`;
    await this.moveFileToFolder(file, targetPath);
  }
  /**
   * Check if file was created from a canvas view
   */
  isCreatedFromCanvas(file) {
    var _a;
    const canvasLeaves = this.app.workspace.getLeavesOfType("canvas");
    if (canvasLeaves.length === 0)
      return false;
    const rootPath = this.app.vault.getRoot().path;
    return ((_a = file.parent) == null ? void 0 : _a.path) === rootPath;
  }
  /**
   * Get the currently active canvas file
   */
  getActiveCanvasFile() {
    const canvasLeaves = this.app.workspace.getLeavesOfType("canvas");
    if (canvasLeaves.length === 0)
      return null;
    const activeLeaf = canvasLeaves.find((leaf) => {
      const view2 = leaf.view;
      return (view2 == null ? void 0 : view2.file) instanceof import_obsidian.TFile;
    });
    if (!activeLeaf)
      return null;
    const view = activeLeaf.view;
    const canvasFile = view == null ? void 0 : view.file;
    if (canvasFile instanceof import_obsidian.TFile && canvasFile.extension === "canvas") {
      return canvasFile;
    }
    return null;
  }
  /**
   * Calculate the target folder path based on canvas file
   */
  getTargetFolderPath(canvasFile) {
    if (!canvasFile.parent)
      return null;
    const canvasName = canvasFile.basename;
    const canvasParentPath = canvasFile.parent.path;
    const folderName = `elements-of_${canvasName}`;
    if (!canvasParentPath || canvasParentPath === "/" || canvasParentPath === "") {
      return folderName;
    }
    return `${canvasParentPath}/${folderName}`;
  }
  /**
   * Ensure the target folder exists, create if needed
   */
  async ensureFolderExists(folderPath) {
    try {
      const folder = this.app.vault.getAbstractFileByPath(folderPath);
      if (folder)
        return;
      await this.app.vault.createFolder(folderPath);
    } catch (error) {
      console.warn(`Could not create folder ${folderPath}:`, error);
    }
  }
  /**
   * Get a unique file name by appending numbers if conflicts exist
   */
  async getUniqueFileName(folderPath, fileName) {
    const baseName = fileName.replace(/\.md$/, "");
    const extension = ".md";
    const targetPath = `${folderPath}/${fileName}`;
    const existingFile = this.app.vault.getAbstractFileByPath(targetPath);
    if (!existingFile) {
      return fileName;
    }
    let counter = 1;
    let newFileName;
    let newPath;
    do {
      newFileName = `${baseName} ${counter}${extension}`;
      newPath = `${folderPath}/${newFileName}`;
      const file = this.app.vault.getAbstractFileByPath(newPath);
      if (!file) {
        return newFileName;
      }
      counter++;
    } while (counter < 1e3);
    return `${baseName} ${Date.now()}${extension}`;
  }
  /**
   * Move file to target folder with error handling
   */
  async moveFileToFolder(file, targetPath) {
    try {
      await this.app.fileManager.renameFile(file, targetPath);
    } catch (error) {
      console.error(`Failed to move file ${file.path} to ${targetPath}:`, error);
    }
  }
};
